### PR TITLE
[wgsl] Add location validation tests

### PR DESCRIPTION
**Pull request by dj2**
This CL adds more validation tests for the `location` attribute.

Fixes: #1453

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Review by alan-baker — COMMENTED** [review]
Seems like the following cases are missing:
* invalid in a compute stage
* only scalar types (e.g. vec2(1,1) is invalid)
* works on input and output
* works on member of a structure
* only applies to numeric scalar or vectors 

Not sure if these are covered elsewhere, but they are all listed explicitly in the location attribute entry.

**Comment by dj2** [comment]
They exist in that test file already, they're just existing. Github collapses existing content, so you need to expand the collapsed section to see them.

**Comment by alan-baker** [comment]
> They exist in that test file already, they're just hiding. Github collapses existing content, so you need to expand the collapsed section to see them.

Took a look, I think `@location(vec2(1,1))` would be worth adding as invalid. Otherwise I agree it looks covered.

**Comment by dj2** [comment]
done.

**Review by alan-baker — APPROVED** [review]

**Pull request merged**
