### PR TITLE
Add dummy targets to render pipelines

### PR DESCRIPTION
**Pull request by sagudev**
Issue: #3806 

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)
- [x] Test have be tested with compatibility mode validation enabled and behave as expected. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [x] Tests are properly located in the test tree.
- [x] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [x] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [x] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Review by kainino0x — APPROVED** [review]
Not sure if you're still planning more changes, but this LGTM as is.

**Comment by sagudev** [comment]
> Not sure if you're still planning more changes, but this LGTM as is.

I only need to do some more testing.

**Comment by sagudev** [comment]
Edge still passes all tests, while firefox has some new passes.

**Comment by kainino0x** [comment]
Great!

**Pull request merged**
