### PR TITLE
Ignore compilation error in writeTimestamp tests

### PR DESCRIPTION
**Pull request by haoxli**
As writeTimestamp API has been removed from SPEC and webgpu types, the tests including it will cause build error when rolling latest types.

Add pass's timestampWrites tests for destoryed query set.

Issue: #

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [x] Tests are properly located in the test tree.
- [x] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [x] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [x] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by kainino0x** [comment]
I updated these recently in #3167 and intentionally kept the tests for writeTimestamp. We're definitely going to try to add it back in some form, and I think if we remove the tests then we will end up forgetting about them and having to rewrite them someday.

I think it would be OK to keep writeTimestamp in the types. But if we don't do that, we can use unsafe casts, like:

```ts
interface WithWriteTimestamp : GPUCommandEncoder {
    writeTimestamp(querySet: GPUQuerySet, queryIndex: GPUSize32): undefined;
}

(encoder.encoder as WithWriteTimestamp).writeTimestamp(/* ... */);
```

**Comment by haoxli** [comment]
We can keep types to align with the spec. 
Could we simply add "@ts-ignore" before writeTimestamp API to ignore the compile error?

**Comment by kainino0x** [comment]
Not sure `@ts-ignore` works with our lint setup, but yes it would be fine to turn off the type checking here. You can use `as any` + `eslint-disable-next-line @typescript-eslint/no-explicit-any`.

**Review by kainino0x — APPROVED** [review]
I replaced the two-line eslint+tsc ignore with just `as any` and a lint ignore. I prefer this because it is a more controlled escape hatch compared with `@ts-ignore`.

I also found a different way to include writeTimestamp in the list of encoder commands without `as any`.

LGTM, please merge if this looks good to you.

**Comment by haoxli** [comment]
LGTM, thanks for the update.

**Pull request merged**
