### PR TITLE
wgsl: Add discussion about how OOB-ness is inherited

### PR DESCRIPTION
**Pull request by zoddicus**
Covers the details of scalar, vector, and matrix operations.

Also includes a few minor cleanups to other sections of the doc that I made while reviewing the text.

Issue #3191

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by zoddicus** [comment]
I will review the CTS code and send up a seperate PR if there are code-side changes needed to conform with this discussion.

**Review by jzm-intel — COMMENTED** [review]
Looks good to me, thanks!

I think the description added here is what we are already trying to emplace in the CTS implementation now, right? I think I can learn the general idea of `simulating the possible computation steps (maybe multiple path) and flow the intermediate OOB to the result` when following the implementation, and element-wise operation do such simulation in element-wise manner to get a possibly OOB-mixed result expectation.

**Review by ben-clayton — APPROVED** [review]
LGTM

**Comment by zoddicus** [comment]
> Looks good to me, thanks!
> 
> I think the description added here is what we are already trying to emplace in the CTS implementation now, right? I think I can learn the general idea of `simulating the possible computation steps (maybe multiple path) and flow the intermediate OOB to the result` when following the implementation, and element-wise operation do such simulation in element-wise manner to get a possibly OOB-mixed result expectation.

The CTS is currently slightly inconsistent in this regard, but this is what was intended to be implemented. I have a WIP patch that fixes up a number of places that were incorrect that I should be sending up for review later today.

**Pull request merged**
