### PR TITLE
WIP: Remove infinities from values for f32 tests

### PR DESCRIPTION
**Pull request by zoddicus**
This patch removes the use of infinities in inputs for all of the f32 tests. It is also introduces a framework for specifying filtering of inputs to const-eval tests, so that inputs that would cause validation errors can be avoided.

This patch currently does not have tests covering the new *LargestIntermediateValue functions, those will be added before final review and merge.

This does NOT remove the generation of NaN/Infinity via 1/0 when writing out testing values. That will be handled in a follow on PR, since that may have impact outside of the numeric tests.

Issue #2020

<hr>

**Requirements for PR author:**

- [ ] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [ ] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by zoddicus** [comment]
PTAL and do a first high level review pass. I plan on implementing testing for the new functions added, once the overall structure of the change is approved.

**Comment by ben-clayton** [comment]
There's an awful lot of code here, but what I've looked at so far looks good.

The Largest Intermediate Value generation looks rather fragile. Maybe I'm missing something, but I was rather expecting that this would be handled by your interval range system? Maybe we should arrange a meeting to discuss the problems you're solving here.

**Comment by zoddicus** [comment]
The first chunk, removing from infinities from input ranges, is up for review https://github.com/gpuweb/cts/pull/2056

**Comment by zoddicus** [comment]
This is superseded by other changes I have uploaded.

**Pull request closed without merging**
