### PR TITLE
Fix types deprecations

### PR DESCRIPTION
**Pull request by kainino0x**
This fixes (or suppresses) deprecations that are detectable at the source level. (There are still a lot of usages of deprecated enums, deprecated versions of dictionaries, etc. which can't be detected.)

It adds the linter for deprecation but doesn't enable it because we still have the deprecation of `.params()` to clean up.

<hr>

**Author checklist for test code/plans:**

- [x] All outstanding work is tracked with "TODO" in a test/file description or `.unimplemented()` on a test.
- [x] New helpers, if any, are documented in `helper_index.md`.
- [x] (Optional, sometimes not possible.) Tests pass (or partially pass without unexpected issues) in an implementation. (Add any extra details above.)
    
**[Reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md) for test code/plans:** (Note: feel free to pull in other reviewers at any time for any reason.)

- [x] The test path is reasonable, the [description](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) "describes the test, succinctly, but in enough detail that a reader can read only the test plans in a file or directory and evaluate the completeness of the test coverage."
- [x] Tests appear to cover this area completely, except for outstanding TODOs. Validation tests use control cases.
    (This is critical for coverage. Assume anything without a TODO will be forgotten about forever.)
- [x] Existing (or new) test helpers are used where they would reduce complexity.
- [x] TypeScript code is readable and understandable (is unobtrusive, has reasonable type-safety/verbosity/dynamicity).

### CODE REVIEW

**Comment by kainino0x** [comment]
@Richard-Yunchao PTAL

**Comment by kainino0x** [comment]
I forgot to mention you can review one commit at a time, and it should be easier.

**Review by Richard-Yunchao — APPROVED** [review]
LGTM. I noticed that you also made a lot of changes in webgpu/types project recently. Now both webgpu/cts and webgpu/types are almost aligned with latest WebGPU spec, except for a couple TODOs. Good work! 

Meanwhile, let's see whether the Chromium bots are fine when we roll this PR into Chromium. This PR changed a lot of code. It is very likely that the Chromium bots will be fine but it is hard to verify the running result manually.

**Comment by Richard-Yunchao** [comment]
Feel free to merge, @kainino0x .

**Comment by kainino0x** [comment]
> Meanwhile, let's see whether the Chromium bots are fine when we roll this PR into Chromium. This PR changed a lot of code. It is very likely that the Chromium bots will be fine but it is hard to verify the running result manually.

Agreed. I'm pretty sure it will work (for most of the deprecations, I checked to make sure we actually implement the new thing). Also just now I checked a few tests to make sure they still run, and they do.

**Comment by Richard-Yunchao** [comment]
> > Meanwhile, let's see whether the Chromium bots are fine when we roll this PR into Chromium. This PR changed a lot of code. It is very likely that the Chromium bots will be fine but it is hard to verify the running result manually.
> 
> Agreed. I'm pretty sure it will work (for most of the deprecations, I checked to make sure we actually implement the new thing). Also just now I checked a few tests to make sure they still run, and they do.

Yeah. Chromium bots are all green for this PR: https://chromium-review.googlesource.com/c/chromium/src/+/2830333.

**Comment by kainino0x** [comment]
awesome, thanks for checking that!

**Pull request merged**
