### PR TITLE
Add a test which prints what environment it runs in

### PR DESCRIPTION
**Pull request by kainino0x**
This is very useful for making sure tests are running in the environment (main thread vs various worker types, etc.) that we expect them to be.

Dry run: https://dawn-review.googlesource.com/c/dawn/+/182163

Example outputs from my machine:

```json
{
  "globalScope": "DedicatedWorkerGlobalScope",
  "globalTestConfig": {
    "enableDebugLogs": false,
    "maxSubcasesInFlight": 500,
    "noRaceWithRejectOnTimeout": false,
    "unrollConstEvalLoops": false,
    "compatibility": false,
    "forceFallbackAdapter": false,
    "logToWebSocket": true
  },
  "defaultRequestAdapterOptions": {
    "powerPreference": "low-power"
  },
  "adapterInfo": {
    "vendor": "apple",
    "architecture": "common-3",
    "device": "",
    "description": ""
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
}
```

```json
{
  "globalScope": "Window",
  "globalTestConfig": {
    "enableDebugLogs": false,
    "maxSubcasesInFlight": 500,
    "noRaceWithRejectOnTimeout": false,
    "unrollConstEvalLoops": false,
    "compatibility": false,
    "forceFallbackAdapter": false,
    "logToWebSocket": false
  },
  "defaultRequestAdapterOptions": null,
  "adapterInfo": {
    "vendor": "apple",
    "architecture": "common-3",
    "device": "0x0000",
    "description": "Apple M1 Pro",
    "driver": "Metal driver on macOS Version 14.4.1 (Build 23E224)",
    "backend": "metal",
    "type": "integrated GPU",
    "memoryHeaps": {
      "0": {
        "size": 22906503168,
        "properties": 23
      }
    },
    "d3dShaderModel": null,
    "vkDriverVersion": null
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
}
```

Issue: https://crbug.com/330573129

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)
- [x] Test have be tested with compatibility mode validation enabled and behave as expected. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Review by greggman — APPROVED** [review]
do you want to print adapter info in this or another test?

**Comment by kainino0x** [comment]
Unfortunately it turns out we don't save the logs from this test when it runs in Chromium, because it passes. Need to think if there's a way we can get it to work.

I dry ran it here along with another PR:
https://dawn-review.googlesource.com/c/dawn/+/181560?checksPatchset=5&tab=checks
https://ci.chromium.org/ui/p/chromium/builders/try/mac-arm64-dawn-rel/3269/test-results?sortby=&groupby=&q=environment

**Comment by greggman** [comment]
Just throwing this out there.... we could mark it as expected to fail and make it always fail

**Comment by kainino0x** [comment]
At Loko's suggestion I'll consider just printing all this info when a test fails (maybe once per page load)

**Comment by kainino0x** [comment]
> Just throwing this out there.... we could mark it as expected to fail and make it always fail

Thought of this too. It wouldn't be super ideal to have a conformance test that can't pass, but it's an option.

**Comment by kainino0x** [comment]
Could also try using `console.log` to output this. The shard logs might capture those even if the test logs don't? I'm not sure, I should try locally.

**Comment by kainino0x** [comment]
Sorry, right after re-requesting your review I figured out how to simplify using a replacer function. PTAL

**Review by greggman — APPROVED** [review]
lgtm

**Pull request merged**
