### PR TITLE
Update defaultQueue->queue, OUTPUT_ATTACHMENT->RENDER_ATTACHMENT to match latest spec

### PR DESCRIPTION
**Pull request by toji**
Simple update of any  instance of `defaultQueue` to `queue`. This will bring the CTS inline with the most recent spec changes and, once it rolls, significantly reduce the amount of deprecation warnings spamming the Chrome build bots. :)

-----

- [x] New helpers, if any, are documented in `helper_index.md`.
- [x] Incomplete tests, if any, are marked with TODO or `.unimplemented()`.

**[Review requirements](https://github.com/gpuweb/cts/blob/main/docs/reviews.md) are satisfied for:**

- [x] WebGPU readability
- [ ] TypeScript readability

### CODE REVIEW

**Comment by toji** [comment]
Hm... What does the CI run against and how do we update it to something that recognizes the new attribute name?

**Comment by Kangz** [comment]
It uses https://github.com/gpuweb/types that should be updated and rolled in the CTS.

**Comment by kainino0x** [comment]
We can do this as an incremental fix to the types, but we're also really overdue for a full update to match the latest spec.

**Review by kainino0x — COMMENTED** [review]
LGTM but will need types update

**Comment by toji** [comment]
Also added the matUTPUT_ATTACHMENT->RENDER_ATTACHMENT to this change to match the corresponding change in https://github.com/gpuweb/types/pull/41

**Review by kainino0x — APPROVED** [review]

**Pull request merged**
