### PR TITLE
Generate many WPT html files for infra that doesn't support variants

### PR DESCRIPTION
**Pull request by kainino0x**
`npx grunt wpt` will now generate an extra subdir in `out-wpt/multi/webgpu`.

(Like the rest of the build, these should show up [in the `gh-pages` branch](https://github.com/gpuweb/cts/tree/gh-pages/out-wpt), so it'll be possible to get the latest code from there without building anything locally.)

Issue: None

<hr>

**Requirements for PR author:**

- [x] ~All missing test coverage is tracked with "TODO" or `.unimplemented()`.~ N/A
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [x] ~Tests are properly located in the test tree.~ N/A
- [x] ~[Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.~ N/A
- [x] ~Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**~ N/A
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by sagudev** [comment]
Any progress?

**Comment by kainino0x** [comment]
This was a proposed change to help WebKit integration (@litherum)... I don't know if they ended up needing it?

@sagudev if you have a testbed in which to test this PR, I'd be happy to bring it up to speed and land it once you've been able to test it.

**Comment by kainino0x** [comment]
I talked with @litherum today and I'm going to hopefully do some work soon to do chunking based on measurements of test time so we can generate chunks that stay under a few seconds. I don't know what form this will take yet, but it'll probably be some time before I complete that, so let me know if landing something simpler like this first would be helpful.

**Comment by kainino0x** [comment]
Filed https://github.com/gpuweb/cts/issues/2749

**Comment by sagudev** [comment]
With introduction of [new chunking algorithm in wpt](https://github.com/web-platform-tests/wpt/pull/40020), servo would not need be needing this.

**Comment by kainino0x** [comment]
Thanks for letting me know about that. Unfortunately AFAIK none of the big browsers actually use the upstream WPT harness. IIRC at least some would like to, but I am not aware offhand of any progress on the Chromium side.

**Pull request closed without merging**
