### PR TITLE
Update subcaseMS of web_platform,copyToTexture,ImageBitmap

### PR DESCRIPTION
**Pull request by jzm-intel**
This PR clean up web_platform,copyToTexture,ImageBitmap cases that has subcaseMS <=0 in listing_meta.json, to reduce the validation warning.
This PR also rename some test case parameter to shorten the WPT generated chunk file name.

Issue: #2939

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by jzm-intel** [comment]
Unfortunately, it seems that changing the `subcaseMS` value to non-zero for any these cases
```
webgpu:compat,api,validation,encoding,programmable,pipeline_bind_group_compat:twoDifferentTextureViews,render_pass,used:*
webgpu:web_platform,copyToTexture,ImageBitmap:from_ImageData:*
webgpu:web_platform,copyToTexture,ImageBitmap:from_canvas:*
```
will fail the CI with errors similar to following one:
```
Running "run:generate-wpt-cts-html-chunked2sec" (run) task
Error: Generated test variant would produce too-long -actual.txt filename. Possible solutions:
- Reduce the length of the parts of the test query
- Reduce the parameterization of the test
- Make the test function faster and regenerate the listing_meta entry
- Reduce the specificity of test expectations (if you're using them)
webgpu:web_platform,copyToTexture,ImageBitmap:from_ImageData:alpha="none";orientation="none";colorSpaceConversion="default";srcDoFlipYDuringCopy=false;dstColorFormat="rgba8unorm-srgb";*
    at assert (/home/runner/work/cts/cts/src/common/util/util.ts:[38](https://github.com/gpuweb/cts/actions/runs/6323417500/job/17170949177#step:5:39):11)
    at /home/runner/work/cts/cts/src/common/tools/gen_wpt_cts_html.ts:206:13
Warning: non-zero exit code 1 Use --force to continue.
```

**Comment by jzm-intel** [comment]
Rename some testcase parameter to shorten the length of chunk filename help fix the error.

**Review by greggman — APPROVED** [review]
lgtm

**Review by shaoboyan — APPROVED** [review]
lgtm, thanks for renaming!

**Comment by jzm-intel** [comment]
Thanks for reviewing!

**Review by kainino0x — COMMENTED** [review]
Yeah, I had to leave these warnings in to start because I didn't want to go fixing tests. Thank you for fixing it!

**Pull request merged**
