### PR TITLE
Implement api,operation,rendering,draw:vertex_attributes,basic

### PR DESCRIPTION
**Pull request by austinEng**
-----

- [x] New helpers, if any, are documented in `helper_index.md`.
- [x] Incomplete tests, if any, are marked with TODO or `.unimplemented()`.

**[Review requirement](https://github.com/gpuweb/cts/blob/main/docs/reviews.md) checklist:**

- [x] WebGPU readability
- [x] TypeScript readability

### CODE REVIEW

**Review by kainino0x — APPROVED** [review]
Assuming this does something roughly resembling passing in a browser, LGTM

**Comment by austinEng** [comment]
Passes in Canary on Mac and Windows for me.

**Comment by kainino0x** [comment]
@austinEng i think the plan for https://github.com/gpuweb/cts/blob/main/src/webgpu/api/operation/vertex_state/correctness.spec.ts overlaps with this, could I ask you to check and see if we can clean up the duplication?

**Comment by kainino0x** [comment]
The test in this PR may not overlap, not sure, but the unimplemented one also might

**Comment by kainino0x** [comment]
see #541

**Pull request merged**
