### PR TITLE
fragment builtins: document missing test, or other places to find them               

### PR DESCRIPTION
**Pull request by dneto0**
<hr>

**Requirements for PR author:**

- [ ] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [ ] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by dneto0** [comment]
@greggman thanks for doing all the hard work.  I added this to make explicit the missing coverage that I could see.

**Review by greggman — APPROVED** [review]
`sample_mask` output seems to be tested here

src/webgpu/api/operation/render_pipeline/sample_mask.spec.ts

`frag_depth` output seems to be indirectly tested here

src/webgpu/api/operation/rendering/depth_clip_clamp.spec.ts

Maybe a comment?

**Comment by dneto0** [comment]
> `sample_mask` output seems to be tested here
...
> `frag_depth` output seems to be indirectly tested here
...
> Maybe a comment?

Thanks!  As they say, the best way to get the right answer on the Internet is to post the wrong answer.

Changed the text to point to those other places, and to keep the sample_mask input test as unimplemented, but with a suggestion to extend the sample_mask output test. (I'd say it's a *strong* recommendation, but hopefully it will be obvious.)

PTAL. @greggman

**Review by greggman — APPROVED** [review]
lgtm

**Pull request merged**
