### PR TITLE
validate dp4a builtins (packed_4x8_integer_dot_product language feature)

### PR DESCRIPTION
**Pull request by dneto0**
Issue: #3180

Builds on #3058

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by dneto0** [comment]
The only changed files vs. the upstream PR are in src/webgpu/shader/validation/expression/call/builtin

There's a lot of overlap between the files, but I think our chosen style is to have one file per builtin function.  It probably merits refactoring a bit.

**Review by Jiawei-Shao — APPROVED** [review]
LGTM! Thanks!

**Comment by dneto0** [comment]
#3058 landed, and I rebased on top of that.

**Comment by dneto0** [comment]
dawn.node does not implement GPU.wgslLanguageFeatures.  https://bugs.chromium.org/p/dawn/issues/detail?id=2260
I'd like to fix that first before landing this change.

**Comment by dneto0** [comment]
Rebased on main.
Tested in dawn.node now also.

**Pull request merged**
