### PR TITLE
Use local grunt

### PR DESCRIPTION
**Pull request by greggman**
That way there are less conflicts with other projects

### CODE REVIEW

**Comment by kainino0x** [comment]
IIUC, installing grunt globally is not supposed to conflict with other projects, because I think it's just a wrapper that calls into the grunt installed in the local node_modules.

That said, this change would be fine but I'd like to keep a note that it can be installed globally too.

(side note: at some point on one of my machines, `npx somecommand` would take about 5-10 seconds longer than `./node_modules/.bin/somecommand` due to some kind of superfluous package updating or something. Not happening anymore though, so I guess it's fine.)

**Comment by greggman** [comment]
I guess it's just a pet peeve. Any project that requires me to install things globally seems out of date, left over from the 90s. There may be other commands named `grunt`. Given it's trivial not to have to install it globally I'd suggest it's better not to even suggest it. Some projects even go so far as to [put node itself in their package.json](https://www.npmjs.com/package/node). You still need one to run npm but it doesn't have to be the same one the project itself uses.

**Comment by greggman** [comment]
Let me add this is one reason I was never able to run the WebGL harness

https://github.com/KhronosGroup/WebGL/tree/master/tools

Because it requires a ton of incompatible prerequisites. If it used everything locally all those instructions become simple and conflicts disappear.

It would be nice not to propagate the same issues in this repo. I get that grunt here might be minor but it's the precedent that starts it off.

**Comment by kainino0x** [comment]
That's convincing enough for me.

Actually, the idea of putting node in the package.json sounds interesting. Do you know enough about that to recommend whether we should do it too?

**Pull request merged**
