### PR TITLE
Make cmdline.ts runnable when compiled as cmdline.js as well

### PR DESCRIPTION
**Pull request by austinEng**
Issue: #

<hr>

**Requirements for PR author:**

- [ ] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [ ] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by austinEng** [comment]
If you compile everything into a path like `path/to/compiled-js-out/src` and then run it with plain `node`, without  `ts-node`

but, it might be better to automatically change directories to where the script wants to be run from

**Comment by kainino0x** [comment]
We have that in the form of `out-node/` but it doesn't have `src/` in it; `src/*` corresponds to `out-node/*`.

Also how can the script know where it should `cd` to? would that be a command line parameter?

It occurs to me I have no idea why this script actually needs to be run from the root, since all of the imports are relative. There's probably a reason, but I should have documented it...

**Comment by austinEng** [comment]
maybe cd to `dir(dir(dir(dir(__filename))))` ? or if we don't actually need this check, then that's great too

**Comment by kainino0x** [comment]
Found another solution

**Pull request closed without merging**
