### PR TITLE
Test maxBindGroupsPlusVertexBuffers limits

### PR DESCRIPTION
**Pull request by greggman**
Testing this is fairly confusing because there's so many things in play. I'm also not sure related tests don't need revisiting.

Testing `maxBindGroupsPlusVertexBuffers` implies to me, testing `maxBindGroups` and `maxVertexBuffers` at their max values. `maxBindGroups` in turn, implies setting `maxSampledTexturesPerShaderStage`, `maxSamplersPerShaderStage`, `maxStorageBuffersPerShaderStage`, `maxStorageTexturesPerShaderStage`, and `maxUniformBuffersPerShaderStage`. That's because, given the combination of parameters, there's no guarantee you can hit `maxBindGroups` if those don't sum to more than `maxBindGroups`.

And, similarly, testing `maxVertexBuffers` implies testing `maxVertexAttributes`, or so it feels. Like, in order to actually make a pipeline that will use `maxVertexBuffers`, the pipeline needs `maxVertexAttributes >= maxVertexBuffers`. 

Note that this doesn't currently test manually created layouts via `createPipelineLayout` + vertex buffers, it only test (1) `createPipeline` with `layout: 'auto'` and (2) `drawXXX`

I can add that but it would be nice to get some feedback on this first

<hr>

**Requirements for PR author:**

- [X] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [X] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [X] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by greggman** [comment]
sorry, I forgot to add the file 😅

**Comment by kainino0x** [comment]
> And, similarly, testing `maxVertexBuffers` implies testing `maxVertexAttributes`, or so it feels. Like, in order to actually make a pipeline that will use `maxVertexBuffers`, the pipeline needs `maxVertexAttributes >= maxVertexBuffers`.

Does GPUVertexBufferLayout.attributes actually have to be non-empty? I can't find a rule saying that, though there is one bit of spec text that assumes it:

> Let lastStride be max(attribute.offset + sizeof(attribute.format)) for each attribute in buffers[slot].attributes.

**Comment by mwyrzykowski** [comment]
> Does GPUVertexBufferLayout.attributes actually have to be non-empty? I can't find a rule saying that, though there is one bit of spec text that assumes it:
> 
> > Let lastStride be max(attribute.offset + sizeof(attribute.format)) for each attribute in buffers[slot].attributes.

I don't think it needs to be non-empty and I think there are CTS tests which test that. My reading is that lastStride would be zero if all the attributes are empty.

**Comment by kainino0x** [comment]
That makes logical sense. I think the text is ambiguous as written though.

**Comment by kainino0x** [comment]
Sorry, couldn't find time to review this today.

**Pull request closed without merging**
