### PR TITLE
Refactor discard test for no storage buffers

### PR DESCRIPTION
**Pull request by greggman**

### CODE REVIEW

**Review by alan-baker — COMMENTED** [review]
Still reviewing, but what do you you think instead about making the choice between framebuffer and storage buffer a subcase to each test and skip the storage buffer version on compat implementations that don't support them? To me, the benefit would be that the same tests are run everywhere so and it's not the case that the test functions differently depending on the hardware. It also ensures we cover discard functionality more thoroughly.

**Comment by greggman** [comment]
sgtm. i"ll update

**Comment by greggman** [comment]
updated. please take a look.

**Comment by greggman** [comment]
ah, I made them cases, would be prefer subcases? There appears to be only one expectation in dawn related to this and it should be fine is I think.

**Review by alan-baker — APPROVED** [review]

**Pull request merged**
