### PR TITLE
Swapchain format

### PR DESCRIPTION
**Pull request by jchen10**
Issue: #

<hr>

**Requirements for PR author:**

- [ ] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [ ] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by kainino0x** [comment]
FYI this sends notifications to people who are watching this repo - since this is your own branch you can just push to it directly.

**Comment by jchen10** [comment]
> FYI opening PRs sends notifications to people who are watching this repo - since this is your own branch you can just push to it directly.

Nice, thanks for the reminder.

**Comment by jchen10** [comment]
> FYI opening PRs sends notifications to people who are watching this repo - since this is your own branch you can just push to it directly.

@kainino0x I'm unable to push directly to my own branch. Likely I'm missing some gerrit permission.
  >>  ! [remote rejected]   jie-DryRun -> jie-DryRun (prohibited by Gerrit: not permitted: update)

**Comment by kainino0x** [comment]
That sounds like you're pushing to your own branch on Gerrit's mirror https://chromium.googlesource.com/external/github.com/gpuweb/cts
You can't do that, but you can push to your branch in this GitHub repository (rather than using a PR to update it) and then wait for the mirror to pick it up.

**Comment by jchen10** [comment]
Aha, it works. So nice of you, thanks!

**Pull request merged**
