### PR TITLE
Reverts

### PR DESCRIPTION
**Pull request by ben-clayton**
This CL reverts 5 changes that landed on Friday without code-review:
76e56df43e92187f9961679a35b254dc65432235
691e6b4606de182dadedf6eacab09b5e9ab2836a
f42aeb4d43526482a59e2b49533520ebd03dec63
da1527dba015b610c46ba523312b462e532adca8
a8f254a08954557a80c6f2ff9422c36fadcac039

One or more of these changes appear to be causing build issues for developers, and the author is now on vacation for a number of weeks.

### CODE REVIEW

**Comment by zoddicus** [comment]
Specifically the errors that are occuring when new tests are being added to the CTS (https://github.com/gpuweb/cts/actions/runs/6148032860/job/16680835944?pr=2926), and look like this:
```
Running "run:validate" (run) task
Build completed! Running checks/testsWARNING: subcaseMS≤0 found in listing_meta.json (allowed, but try to avoid):
  webgpu:compat,api,validation,encoding,programmable,pipeline_bind_group_compat:twoDifferentTextureViews,render_pass,used:*
  webgpu:web_platform,copyToTexture,ImageBitmap:from_ImageData:*
  webgpu:web_platform,copyToTexture,ImageBitmap:from_canvas:*
ERROR: Tests missing from listing_meta.json. Please add the new tests (set subcaseMS to 0 if you cannot estimate it):
  webgpu:shader,execution,expression,binary,af_matrix_addition:matrix:*
  webgpu:shader,execution,expression,unary,f16_arithmetic:negation:*

/home/runner/work/cts/cts/src/common/util/util.ts:38
    throw new Error(msg && (typeof msg === 'string' ? msg : msg()));
          ^
Error: 
    at assert (/home/runner/work/cts/cts/src/common/util/util.ts:38:11)
    at crawl (/home/runner/work/cts/cts/src/common/tools/crawl.ts:155:11)
Warning: non-zero exit code 1 Use --force to continue.

Aborted due to warnings.
Error: Process completed with exit code 3.
```

There is some documentation in the added files about creating new entries, but it feels confused on how critical these values are. The documentation seems to imply doing a best effort/eyeballing it is fine, but the values not being present are throwing a hard errors in 'run:validate', which feels excessive for something that can be eyeballed.

**Review by zoddicus — APPROVED** [review]

**Review by zoddicus — APPROVED** [review]

**Comment by ben-clayton** [comment]
> This CL reverts 5 changes that landed on Friday without code-review:

I think Github was just being buggy for a while. The PR is now showing up on the CLs, and it passed presubmits.

@austinEng theorises that @zoddicus's PR may have landed between the presubmits passing on @kainino0x 's change and that change landing. If this is the case, we need to figure out how to `add the new tests`  as the error asks.

**Comment by zoddicus** [comment]
The negation PR that I landed this morning was up for review on Thursday, so wouldn't have seen the change to the checks and was autorebased by github when landing this morning, so that wouldn't have re-run the checks, which is why it didn't hit the issue.

I manually rebased & updated https://github.com/gpuweb/cts/pull/2926 since I had review comments on it this morning, which is why the checks re-ran.

For some reason GitHub is still not linking the diffs in the repo to the PRs/reviews that were done for me, but if I go to the PR tab I can see the reviews.

**Comment by kainino0x** [comment]
> @austinEng theorises that @zoddicus's PR may have landed between the presubmits passing on @kainino0x 's change and that change landing. If this is the case, we need to figure out how to `add the new tests` as the error asks.

I could have sworn I checked `main` was clean after I landed that PR. Sorry about that.

> There is some documentation in the added files about creating new entries, but it feels confused on how critical these values are. The documentation seems to imply doing a best effort/eyeballing it is fine, but the values not being present are throwing a hard errors in 'run:validate', which feels excessive for something that can be eyeballed.

It's important to keep the list of tests up to date so that tooling can depend on it to know the complete list of tests without running any of the CTS code. It's less important to keep the timing data up to date.

I'll add this to the documentation.

**Pull request closed without merging**
