### PR TITLE
Implement `mix` f32 tests

### PR DESCRIPTION
**Pull request by zoddicus**
Issue #1225

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by zoddicus** [comment]
This is currently broken, uploading for others to see what is going wrong. Will update it with a corrected version before adding reviewers.

**Comment by dj2** [comment]
So, does this need the spec to be updated before landing? Is the intention that a conformant implementation can pass _one_ of the two cases?

**Comment by zoddicus** [comment]
My understanding from the discussion is that a conformant implement has to pass atleast one of the two options, since that is what Vulkan's CTS enforces.

Previously with PRs where the spec needs to change we have landed them with a comment in the could about the spec issue, if they are less restrictive than what currently is in the spec. i.e. no current spec compliant would fail the new version of the test. 

I am fine with leaving this pending until the spec change lands if you prefer, I mostly want it shared so there was a non-local version of the diff for people to look at

**Comment by dj2** [comment]
I'm not sure how to encode the must pass one of the two, having a set of tests that a conformant implementation can _fail_ seems wrong.

Could we define two intervals for the answer and say it has to be in one of the two?

**Comment by zoddicus** [comment]
> I'm not sure how to encode the must pass one of the two, having a set of tests that a conformant implementation can _fail_ seems wrong.
> 
> Could we define two intervals for the answer and say it has to be in one of the two?

I think this is already done?
Instead of having mixInterval return [F32Interval], there is a mixPreciseInterval and mixImpreciseInterval that return F32Interval, and the actual CTS running code in makeCase is responsible for including both of those expectations.

Specifically in `return makeTernaryF32IntervalCase(x, y, z, mixPreciseInterval, mixImpreciseInterval);`
The last param of makeTernaryF32IntervalCase is a spread of F32Intervals, if the result is in any of those intervals it will pass.

This is very similar to how we handle the clamp being either implemented via median of 3 or MinMax. There is two interval generator operations defined, and the actual CTS test uses the spread behaviour to check at least one works.
Each of this implementations has separate unit tests to ensure they behave correctly independently.

The interval array/spread handling is in the make*F32IntervalCase layer of the framework, so that all of the code in f32_interval.ts doesn't need to be aware of there being potentially array of intervals being passed around. I originally attempted, when working on clamp, to have a single clampInterval that returned a [F32Interval], but this introduced a bunch of complexity to interfaces, which bled out into other tests that didn't really need to be aware of this type of return.  The actual test running code could never truly avoid this complexity, since it either needs to allow passing in multiple expectation or take in an array of expectation so all of the complexity has been isolated there.

I really need to get on writing up a doc explaining how all of this hangs together and the reasoning for it.

**Review by dj2 — APPROVED** [review]

**Pull request merged**
