### PR TITLE
Update to webgpu types 0.0.43

### PR DESCRIPTION
**Pull request by Kangz**
PTAL, somehow this rewrote half of the package-lock.json so I'm not sure if I did everything correctly.

### CODE REVIEW

**Comment by austinEng** [comment]
That's odd. I did it on my branch just now and got this:
Maybe you can just patch this in instead.

```diff
-      "version": "0.0.42",
-      "resolved": "https://registry.npmjs.org/@webgpu/types/-/types-0.0.42.tgz",
-      "integrity": "sha512-X3NTj7/7miodS8fc15hpwxP+AfNjzPt6IMUaasBsnicmUIRM/bCLQKazIaRK7Kxh37VPMRKT1vjJ2YQyUELQew==",
+      "version": "0.0.43",
+      "resolved": "https://registry.npmjs.org/@webgpu/types/-/types-0.0.43.tgz",
+      "integrity": "sha512-nzWNUW3o0DlHd2lNU32+RkfaA1xPmDfhAmEE7iKb1osEMh2pnO5NsYCm45DFY4Ffi2i/p/t0wwlxD/lvB7ZHzQ==",
```

**Review by austinEng — APPROVED** [review]
LGTM

**Comment by kainino0x** [comment]
some versions of npm have a tendency to do that, I still have no idea why. I think if you're on a recent enough version it shouldn't happen?

**Comment by austinEng** [comment]
Different major version. I'm on 6.4.11, he was on 7

**Comment by kainino0x** [comment]
ah, I'm also on 6. Annoying issue :\

**Pull request merged**
