### PR TITLE
Add an option to automatically batch large lists of subcases

### PR DESCRIPTION
**Pull request by austinEng**
This adds .batch(n) which adds a batch__ case param and splits
the subcases so that there are at most |n| subcases in a case.
This is helpful when a test will not realistically fit within
the test timeout for a single case.

<hr>

**Author checklist for test code/plans:**

- [ ] All outstanding work is tracked with "TODO" in a test/file description or `.unimplemented()` on a test.
- [ ] New helpers, if any, are documented using `/** doc comments */` and can be found via `helper_index.txt`.
- [ ] (Optional, sometimes not possible.) Tests pass (or partially pass without unexpected issues) in an implementation. (Add any extra details above.)

**[Reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md) for test code/plans:** (Note: feel free to pull in other reviewers at any time for any reason.)

- [ ] The test path is reasonable, the [description](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) "describes the test, succinctly, but in enough detail that a reader can read only the test plans in a file or directory and evaluate the completeness of the test coverage."
- [ ] Tests appear to cover this area completely, except for outstanding TODOs. Validation tests use control cases.
    (This is critical for coverage. Assume anything without a TODO will be forgotten about forever.)
- [ ] Existing (or new) test helpers are used where they would reduce complexity.
- [ ] TypeScript code is readable and understandable (is unobtrusive, has reasonable type-safety/verbosity/dynamicity).

### CODE REVIEW

**Comment by kainino0x** [comment]
This seems OK. Previously I had strayed away from batches because I didn't want there to be too much instability in which test ran in which place. But since this can only be used for subcases, it's less of a problem.

There's been at least one test before where we had to do a loop inside the test itself, because doing the full test setup for every subcase was too expensive - the inner loop was way, way faster. And there's also a recent test which does many shader loads inside one thread which is of course many orders of magnitude faster than individual subcases. Anyway, I don't know if an inner loop would be helpful here, but of note, it should be possible to loop over a CaseParamsBuilder using a for-loop if that's helpful.

**Comment by austinEng** [comment]
> Anyway, I don't know if an inner loop would be helpful here

probably not - compiling distinct pipelines

> There's been at least one test before where we had to do a loop inside the test itself, because doing the full test setup for every subcase was too expensive - the inner loop was way, way faster. 

maybe we can have a separate thing which optionally allows memoizing some data (with a list of dependencies, ex. the device) and passing it into the parameterizations. 
Opt-in because it could cause instability.

**Comment by kainino0x** [comment]
> maybe we can have a separate thing which optionally allows memoizing some data (with a list of dependencies, ex. the device) and passing it into the parameterizations.
> Opt-in because it could cause instability.

This seems like a good idea. We have some places where caching pipelines/etc would be helpful, though not sure whether it would have helped with the specific cases I'm thinking of.

We do have some places where we cache computed stuff, but not just pure-computations, not webgpu objects.

**Comment by austinEng** [comment]
although with pipelines, it should probably hit the cache in the implementation and not be so much of a problem? Could be useful for other resources though like buffers - especially if they're used as read-only. Less risk of unstable test behavior.

**Review by kainino0x — APPROVED** [review]
True, we'd have to look at what cases we actually might need a caching mechanism for.

Anyway, this should lgtm after rebase

**Pull request merged**
