### PR TITLE
Add missing files to out-wpt/ build

### LINKED ISSUE #1092: `npm run wpt` does not populate `out-wpt/common` fully
`npm run wpt` does not produce an `out-wpt/common/internal/file_loader.js` (and a variety of other .js files). The WPT scripts use files from the directory, so in order to use this in a WPT environment, the files have to be copied from `out/`.

### PR DESCRIPTION
**Pull request by kainino0x**
Issue: fixes #1092 (hopefully, I can't easily test this)

<hr>

**Requirements for PR author:**

- [ ] ~All missing test coverage is tracked with "TODO" or `.unimplemented()`.~
- [ ] ~New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.~
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] ~Tests are properly located in the test tree.~
- [ ] ~[Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.~
- [ ] ~Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**~
- [ ] ~Helpers and types promote readability and maintainability.~

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by kainino0x** [comment]
PTAL @ErichDonGubler or @litherum
cc @sagudev

**Comment by sagudev** [comment]
Works for me, the only difference I found was that I do not get source-maps, but they are probably not needed in WPT tests.

**Comment by ErichDonGubler** [comment]
@sagudev, @kainino0x: WFM locally on the Firefox side!

RE: regressing source-maps: Source maps are actually an important tool for diagnosing issues quickly. I'd rather not go without them, unless there's a reason that getting them back is difficult.

**Review by ErichDonGubler — CHANGES_REQUESTED** [review]
@sagudev, @kainino0x: WFM locally on the Firefox side!

RE: regressing source-maps: Source maps are actually an important tool for diagnosing issues quickly. I'd rather not go without them, unless there's a reason that getting them back is difficult.

**Comment by sagudev** [comment]
Source maps were not part out-wpt even before this PR. The difference I was referring to was what was output of [mozilla's vendoring script](https://searchfox.org/mozilla-central/source/dom/webgpu/tests/cts/vendor/src/main.rs#300) (well actually WIP port of it for servo). So I guess source-maps are included only in `out`, from the start (even before this PR).

Sorry for any inconveniences.

**Comment by kainino0x** [comment]
Yeah, there's no regression in source maps. They were already disabled for the wpt build. The reason for this is we didn't want to export both the source and generated files to WPT. But now that we're not actually exporting to WPT (all browsers are vendoring), it would be more reasonable to support.

That said, I'm curious how important sourcemaps are for you. We don't do any minification and the build is carefully set up so that the generated files don't have any transpilation or other generated cruft in them, and get autoformatted after the build, so they look handwritten in almost all cases. Early on we did this so we could abandon typescript and switch to plain javascript if we needed to, but also did it so anyone who isn't writing tests doesn't have to actually think about typescript at all.

**Comment by ErichDonGubler** [comment]
@sagudev:

> Source maps were not part out-wpt even before this PR. The difference I was referring to was what was output of [mozilla's vendoring script](https://searchfox.org/mozilla-central/source/dom/webgpu/tests/cts/vendor/src/main.rs#300) (well actually WIP port of it for servo). So I guess source-maps are included only in `out`, from the start (even before this PR).

I see. This makes much more sense to me than before. 😅 If there's nothing that upstream was attempting to provide in the first place, I see no reason not to merge this (CC @kainino0x).

For what it's worth, I'm the author and maintainer of that script. HMU if you ever have questions about it.

Are you saying that this script is being consumed in Servo? 👀

**Review by ErichDonGubler — APPROVED** [review]

**Pull request merged**
