### PR TITLE
Change .getQueue() to .defaultQueue

### PR DESCRIPTION
**Pull request by romandev**
Spec changes:
https://github.com/gpuweb/gpuweb/pull/490

### CODE REVIEW

**Comment by Kangz** [comment]
LGTM but it doesn't pass the CI because we didn't push the webgpu-types update to npm yet. @kainino0x or @beaufortfrancois I think you both have accesses to do that, can you push a new version of webgpu-types?

**Comment by kainino0x** [comment]
If François can't do it, please update the package.json to point directly
at the GitHub repo instead of npn, which I'm pretty sure is possible. I'll
publish to npm when I'm back from vacation.

**Comment by beaufortfrancois** [comment]
I don't have access to https://www.npmjs.com/package/@webgpu/types sadly.

**Comment by kainino0x** [comment]
Types updated and rolled. Thanks for the patch!

**Pull request merged**
