### PR TITLE
Update to latest WebGPU CTS API

### PR DESCRIPTION
**Pull request by ben-clayton**
`GPUComputePassEncoder.endPass()` -> `end()`
`GPURenderPassEncoder.endPass()` -> `end()`
`GPURenderPassColorAttachment.loadValue` -> `loadOp` / `clearValue`
`GPURenderPassDepthStencilAttachment.depthLoadValue` -> `depthLoadOp` / `depthClearValue`
`GPURenderPassDepthStencilAttachment.stencilLoadValue` -> `stencilLoadOp` / `stencilClearValue`

Issue: #

<hr>

**Requirements for PR author:**

- [ ] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [ ] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [ ] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by ben-clayton** [comment]
Requires the TypeScript definitions to be updated.

**Comment by toji** [comment]
TypeScript definitions have been updated ([PR](https://github.com/gpuweb/types/pull/89)). Published as v0.1.12.

**Review by kainino0x — APPROVED** [review]
LGTM as soon as the types dependency is updated and build succeeds

**Comment by kainino0x** [comment]
(These are all implemented in Chromium, right, so this won't block the roll?)

**Comment by kainino0x** [comment]
An error in the types just got fixed in https://github.com/gpuweb/types/pull/90 and released in v0.0.13

**Comment by ben-clayton** [comment]
> (These are all implemented in Chromium, right, so this won't block the roll?)

Good question. I haven't done a deep-dive to check this.

**Comment by ben-clayton** [comment]
Updated to https://github.com/gpuweb/types/pull/90 v0.0.13, which fixed the `*LoadValue` errors, but another set of API changes have broken a bunch of other things...

**Comment by ben-clayton** [comment]
Merged as https://github.com/gpuweb/cts/pull/1030

**Pull request closed without merging**
