### PR TITLE
Add flip video files for GPUExternalTexture related cts

### PR DESCRIPTION
**Pull request by shaoboyan**
Video with flip display transform matrix is different from  rotation. It is more like a mirror in Y-axis or mirror in X-axis.

Add these video files to test GPUExternalTexture.

Issue: #

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [x] Tests are properly located in the test tree.
- [x] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [x] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Review by kainino0x — APPROVED** [review]
LGTM!
Would it be valuable to have cases that both flip and rotate?

**Comment by kainino0x** [comment]
Ack. That is surprising but maybe `-display_vflip` and `-display_rotation` override each other or something. Would be useful to get to the bottom of it.

**Comment by greggman** [comment]
Do these rotation tests need to be commented out?

If I display the rotation videos in a `<video>` tag or draw them in a 2d canvas they are not rotated. The hflip and vflip videos work though (they are flipped both as a `<video>` and via `drawImage` in a 2d canvas (but not in WebGPU in Chrome so bug there).

Given the rotation ones aren't rotating in `<video>` nor `drawImage` are they invalid? Like, maybe the web platform itself doesn't support rotated video?, or at least not with these files? I verified they are marked as rotated via ffmpeg .... or maybe I don't understand what they're supposed to do. 

Should we comment them out for now?

**Comment by shaoboyan** [comment]
> Do these rotation tests need to be commented out?
> 
> If I display the rotation videos in a `<video>` tag or draw them in a 2d canvas they are not rotated. The hflip and vflip videos work though (they are flipped both as a `<video>` and via `drawImage` in a 2d canvas (but not in WebGPU in Chrome so bug there).
> 
> Given the rotation ones aren't rotating in `<video>` nor `drawImage` are they invalid? Like, maybe the web platform itself doesn't support rotated video?, or at least not with these files? I verified they are marked as rotated via ffmpeg .... or maybe I don't understand what they're supposed to do.
> 
> Should we comment them out for now?

@greggman I made them not rotated in the final result. For example, the rotated 180 degree video is created by rotated content in cw 180 degree and then set the metadata to ccw 180 rotated. I think this could simplified some expectation lists (However, not reached this goal due to we also test visible rectangle). So if you see `video` tag and `drawImage` present the not rotated content, it means they applied rotations already :). P.S. webgl test adopted this behaviour (https://github.com/KhronosGroup/WebGL/blob/main/sdk/tests/conformance/textures/misc/video-rotation.html#L118.)

**Pull request merged**
