### PR TITLE
Add a fence test with time limit

### PR DESCRIPTION
**Pull request by szatkus**
Hi,

I implemented fences today and I discovered that empty `onCompletion` could pass the CTS.

I added a new test case which catches that problem.

Regards

### CODE REVIEW

**Comment by szatkus** [comment]
`Calls to 'setTimeout' are not allowed. WPT (Web Platform Tests) doesn't allow setTimeout. (ban)`

Oh.

**Comment by kainino0x** [comment]
Thanks for the contribution! If you don't mind me asking, what WebGPU implementation are you working on? 🙂 

We have a helper to fix the timeout issue: `src/framework/util/timeout.ts`.
But we also have a helper just for tests like this: `rejectOnTimeout` from `src/framework/util/index.ts`. You should be able to use that one.

**Comment by szatkus** [comment]
My side project: https://github.com/szatkus/kagepu
Basically WebGPU implemented using existing technologies. Quite fun and challenging :)

Thank you for you help. Looks like tests are passing, but Travis still doesn't let the PR. I don't see any meaningful error messages :/

**Comment by szatkus** [comment]
gts was the problem. I forgot about semicolons :/

Funnily enough, when I ran gts on Windows (hey, it's good enough for personal projects) it butchered the whole project by replacing EVERY LF with CRLF. I needed to use my Linux laptop :)

**Comment by kainino0x** [comment]
Oh boy. We absolutely want to support development on windows. There must be a way to configure gts to always use LF.

**Comment by kainino0x** [comment]
> My side project: https://github.com/szatkus/kagepu
> Basically WebGPU implemented using existing technologies. Quite fun and challenging :)

Very cool, thank you for sharing! Sounds like a huge project - good luck!

After looking at this again, I decided to factor out a helper to wrap rejectOnTimeout and pushed it to your branch. LGTM - thanks again for the contribution!

**Comment by kainino0x** [comment]
Hm, tested in chrome and I realized this doesn't quite work because it asks for onCompletion before signalling, which isn't valid. Let me fix this up and also add a test for that.

**Pull request merged**
