### PR TITLE
unittest: FP use correctly rounded dict for frequent number constant

### PR DESCRIPTION
**Pull request by jzm-intel**
This PR try to replace the correcly rounded expectation of frequently used
JS number constant with a dictionary in FP unittests `floating_point.spec.ts`
to improve readablility.

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by jzm-intel** [comment]
This PR is stacked and the intended commit is 0658ab881272eb61c128113f3e8227cf73eb16c0.

This PR intended to add the dictionary for JS Number constant to f32/f16/abstract correctly rounded expectation, and as JS Number and abstract are both actually f64, the JS number mapping to abstract float is accurate instead of rounding, and thus should not be effected by #2993

**Comment by zoddicus** [comment]
That is a very good point (AF needs to be as precise f32). I have had it in the back of my head that I should revisit how ULP is calculated for AF, but I think you are in correct that correctly rounded needs to be revisited too.

I will spend some time on this once the f16 execution tests are done (which they look close to being, given the volume of reviews I have to do today :upside_down_face: )

**Review by zoddicus — APPROVED** [review]
Thank you for improving the quality of the existing code

**Comment by jzm-intel** [comment]
Thanks for reviewing!

**Pull request merged**
