### PR TITLE
Implement api,validation,encoding,programmable,pipeline_bind_group_compat

### PR DESCRIPTION
**Pull request by haoxli**
- Complete unimplemented tests
 - Refactor/Combine existing tests
 - Use existing ValidBindableResource for resource types

<hr>

**Author checklist for test code/plans:**

- [x] All outstanding work is tracked with "TODO" in a test/file description or `.unimplemented()` on a test.
- [x] New helpers, if any, are documented using `/** doc comments */` and can be found via `helper_index.txt`.
- [ ] (Optional, sometimes not possible.) Tests pass (or partially pass without unexpected issues) in an implementation. (Add any extra details above.)

**[Reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md) for test code/plans:** (Note: feel free to pull in other reviewers at any time for any reason.)

- [ ] The test path is reasonable, the [description](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) "describes the test, succinctly, but in enough detail that a reader can read only the test plans in a file or directory and evaluate the completeness of the test coverage."
- [ ] Tests appear to cover this area completely, except for outstanding TODOs. Validation tests use control cases.
    (This is critical for coverage. Assume anything without a TODO will be forgotten about forever.)
- [ ] Existing (or new) test helpers are used where they would reduce complexity.
- [ ] TypeScript code is readable and understandable (is unobtrusive, has reasonable type-safety/verbosity/dynamicity).

### CODE REVIEW

**Comment by kainino0x** [comment]
hey folks, I just noticed this stale PR. Looks like comments were addressed? Should I review from scratch?

**Comment by haoxli** [comment]
Is there any better suggestion for the naming of parameter `useU32Array`? All other comments have been resolved.

**Comment by Kangz** [comment]
If you don't mind I'll let @austinEng finish this review.

**Review by austinEng — APPROVED** [review]
I don't have any better naming suggestions, so LGTM.

**Pull request merged**
