### PR TITLE
Remove non-standard GPUAdapter requestAdapterInfo() method

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR removes the non-standard GPUAdapter requestAdapterInfo() method which was replaced with the GPUAdapter info attribute.

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)
- [x] Test have be tested with compatibility mode validation enabled and behave as expected. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [x] Tests are properly located in the test tree.
- [x] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [x] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [x] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Review by kainino0x — COMMENTED** [review]
LGTM but the `navigator_gpu.ts` change should wait for Firefox so we don't break the entire CTS for them (https://bugzilla.mozilla.org/show_bug.cgi?id=1910206). cc @ErichDonGubler

**Comment by ErichDonGubler** [comment]
Just put patches up for Firefox to add the new `GPUAdapter.info` member, which I expect to land in the next day or so.

**Comment by ErichDonGubler** [comment]
> …the `navigator_gpu.ts` change should wait for Firefox so we don't break the entire CTS for them ([bugzilla.mozilla.org/show_bug.cgi?id=1910206](https://bugzilla.mozilla.org/show_bug.cgi?id=1910206)). cc @ErichDonGubler

Thinking about this, I don't see a reason to block on Firefox's account. I also think it'll only make the `adapter_info` test fail for us? Anyway, if we vendor in the CTS and we don't like seeing test(s) fail, we can (and are on track) to fix this before our next re-vendor. 😛 CC @jimblandy, @teoxoy.

**Comment by kainino0x** [comment]
> I also think it'll only make the `adapter_info` test fail for us?

This PR modifies `getGPU()` to assume `adapter.info` works, though I realize now it's only in the case where `defaultRequestAdapterOptions` is set, which IIRC is when `power_preference` or `compatibility` is set in the CTS global options. Regardless, sounds like we're good to land!

**Review by kainino0x — APPROVED** [review]

**Pull request merged**
