### PR TITLE
Fix exception type for getMappedRange in map_oom

### PR DESCRIPTION
**Pull request by Kangz**
PTAL!

### CODE REVIEW

**Review by kainino0x — APPROVED** [review]
I think this looks good but I think @austinEng should review.

**Comment by austinEng** [comment]
Based on https://github.com/gpuweb/gpuweb/issues/872, I think it should probably stay `RangeError` to match how `new ArrayBuffer` fails.

**Comment by kainino0x** [comment]
Right, that makes sense. MAX_ALIGNED_SAFE_INTEGER is way too large for anything so it makes sense it would match. I'm not sure if we figured out what to do on real cpu-OOM but we can't easily test that here.

**Comment by austinEng** [comment]
I think we said the buffer is an error, you get an async OOM, and we make dummy data so that getMappedRange works (unless it is RangeError)

**Comment by kainino0x** [comment]
Actually, in this test case the buffer itself is invalid (due to OOM), so probably the algorithm should early-out before it "tries" to create an ArrayBuffer? (It's not well defined in the spec yet.) The same thing would happen if the buffer was smaller than the getMappedRange range.

**Comment by kainino0x** [comment]
[race condition above]

Oh yes, I forgot about the buffer OOM being async and having to provide dummy memory for mappedAtCreation. Yeah. RangeError still makes sense to me then.

**Comment by Kangz** [comment]
Gotcha, closing this PR.

**Pull request closed without merging**
