### PR TITLE
Update copyTextureToTexture tests to allow both encodings of -1 for 8-byte snorm formats

### PR DESCRIPTION
**Pull request by austinEng**
Some drivers have been found to swap the encoding of -1 for snorm copies. They are probably internally performing a blit which changes the encoding.

Issue: https://crbug.com/dawn/1047

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [x] Tests are properly located in the test tree.
- [x] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [x] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [x] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

**Comment by austinEng** [comment]
I tried using textureContentIsOKByT2B but it wasn't obvious how since this test is also checking padding bytes of the copy.

**Comment by Kangz** [comment]
> Some drivers have been found to have some values off by 1. This is probably because the copy is implemented as a blit and some rounding occurs.

Note that it shouldn't be that rounding occurs, but that the `MIN` and `MIN+1` values in snorm both represents -1, so if the blit samples `MIN` as -1, then writes it back as `MIN+1` then the value changes, but only this one.

**Review by kainino0x — APPROVED** [review]

**Comment by kainino0x** [comment]
I think this is fine for now and can land. textureContentIsOKByT2B would have tighter behavior if it's really just the MIN vs MIN+1 problem, but we'll need to do something to be able to use it. Thinking either:
- enhance textureContentIsOKByT2B to be able to check the padding bytes
- use textureContentIsOKByT2B (or at least its mechanisms) but ALSO use a buffer check to check the padding bytes

**Comment by austinEng** [comment]
I updated this instead to allow the alternative encoding swap only for 128/129 (0x80 / 0x81). PTAL again

**Review by Kangz — APPROVED** [review]

**Review by kainino0x — APPROVED** [review]

**Pull request merged**
