### PR TITLE
Fix a bug in createTexture validation for multisample

### PR DESCRIPTION
**Pull request by Richard-Yunchao**
If a texture format support multisample, it should be renderable:
color-renderable, depth-renderable, or stencil-renderable.

See gpuweb issue at https://github.com/gpuweb/gpuweb/issues/1522.

This change will fix Dawn issue 731:
https://bugs.chromium.org/p/dawn/issues/detail?id=731.

-----

- [x] New helpers, if any, are documented in `helper_index.md`.
- [x] Incomplete tests, if any, are marked with TODO or `.unimplemented()`.

**[Review requirement](https://github.com/gpuweb/cts/blob/main/docs/reviews.md) checklist:**

- [x] WebGPU readability
- [x] TypeScript readability

### CODE REVIEW

**Comment by Richard-Yunchao** [comment]
Note that I still use a separate column `multisample` to manifest whether each format can support multisample because 1) it is more clear for multisample, we don't need to refer to .renderable for multisample support,  2) it is very unlikely but multisample support might be different with `renderable` in future?  

But if you think we can just remove `multisample` column in capability_info.ts, I am OK to do that :)

**Review by Kangz — APPROVED** [review]

**Comment by kainino0x** [comment]
> Note that I still use a separate column `multisample` to show whether each format can support multisample because 1) it is more clear for multisample, we don't need to refer to .renderable for multisample support, 2) it is very unlikely but multisample support might be different with `renderable` in future?

LGTM, I agree.

**Comment by austinEng** [comment]
You can run the third_party/blink/web_tests/webgpu/roll_webgpu_cts.sh script. Probably needs test expectation updates in third_party/blink/web_tests/WebGPUExpectations

**Comment by Richard-Yunchao** [comment]
Got it. I will have a try.

**Pull request merged**
